# Site settings
name: Chandra Bhushan
title: Chandra Bhushan| Front End Software Engineer
description: Design-minded, detail oriented software engineer passionate about combining beautiful code with beautiful design.
url: https://chandrabhushan.in/
baseurl: ""
email: info@chandrabhushan.in
cover: http://brittanychiang.com/v2/img/og.jpg
logo: http://brittanychiang.com/v2/img/logo-black.png
resume: http://brittanychiang.com/v2/resume.pdf
social:
  - title: email
    url: mailto:info@chandrabhushan.in
  - title: twitter
    url: https://twitter.com/sweetcbk
  - title: instagram
    url: https://instagram.com/sweetcbk
  - title: codepen
    url: http://codepen.io/sweetcbk
  - title: github
    url: https://github.com/sweetcbk
  - title: linkedin
    url: https://www.linkedin.com/in/sweetcbk

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-minifier
  - jekyll-sitemap
